### ISSUE TITLE
Tests removed while OpenFisca Core upgrade required

### ISSUE THREAD

**Issue by verbman** [digitalaotearoa/openfisca-aotearoa#15]
Hi there!
I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
Attempted to get tests passing after OpenFisca core was upgraded

### Here is what I expected to happen:
Tests to pass

### Here is what actually happened:
Tests failed. Essentially it used to be that an input to a test could set a value and it would remain true into the future unless adjusted. The change was that it would only remain true for that period (rather than into the future). OpenFisca core added a feature with this change to let you set multiple periods easily but DIDN'T incorporate the day period into that feature. A number of our tests required testing days over multiple years which makes for a difficult transition.
This was described at the time in [this comment](https://github.com/openfisca/openfisca-core/pull/813#issuecomment-460794327) as being resolved by:
```
persons:
    - id: "Tahi"
      present_in_new_zealand:
        "day:2015-01-01:365": true
```
However the [helpers for this](https://github.com/openfisca/openfisca-core/blob/7566d96d0f21af49370770bb0293cbc772faaff7/openfisca_core/holders/helpers.py) do not support days (only months and years). 

### Here is data (or links to it) that can help you reproduce this issue:
OpenFisca Core: [specific associated code](https://github.com/openfisca/openfisca-core/blob/7566d96d0f21af49370770bb0293cbc772faaff7/openfisca_core/holders/helpers.py) 

Files excluded from testing for now that need to be restored (files changed back to .yaml files):

- openfisca_aotearoa/tests/citizenship/citizenship_leap_days.txt
- openfisca_aotearoa/tests/citizenship/citizenship_more.txt
- openfisca_aotearoa/tests/citizenship/citizenship_presence.txt
- openfisca_aotearoa/tests/immigration/indefinite_stay_enter_and_leave.txt
- openfisca_aotearoa/tests/immigration/indefinite_stay_present_not_entitled.txt

I identify more as a:
- Developer

**Comment by bonjourmauko** [comment]
@verbman could you file a bug-report / feature-proposal in https://github.com/openfisca/openfisca-core? It will make it easier for my proposal to accepted/rejected if the discussion can take place over there.

**Comment by verbman** [comment]
This issue will be resolved by Pull Request: https://github.com/govzeroaotearoa/openfisca-aotearoa/pull/30
