### ISSUE TITLE
Review previous PR's 

### ISSUE THREAD

**Issue by verbman** [digitalaotearoa/openfisca-aotearoa#47]
Hi there!

I really enjoy OpenFisca, but I recently encountered an issue.

### Here is what I did:
We approved a number of PR's into main which still potentially had some outstanding issues
This was done to meet timelines and to converge some complex branching. 
This culminated in version 20.0.0

### Here is what I expected to happen:
This is a note to review those old PR's and the issues raised and readdress them. The below list is meant to be wider than what may require attention. If a PR is included that is cleared of issues just update this issue to reflect that.

- [x] https://github.com/digitalaotearoa/openfisca-aotearoa/pull/46
- [x] https://github.com/digitalaotearoa/openfisca-aotearoa/pull/45
- [x] https://github.com/digitalaotearoa/openfisca-aotearoa/pull/44
- [x] https://github.com/digitalaotearoa/openfisca-aotearoa/pull/43
- [x] https://github.com/digitalaotearoa/openfisca-aotearoa/pull/39
- [x] https://github.com/digitalaotearoa/openfisca-aotearoa/pull/35
- [x] https://github.com/digitalaotearoa/openfisca-aotearoa/pull/33

## Context

I identify more as a:
- Developer

**Comment by bonjourmauko** [comment]
Hi @verbman, I see all mentioned PRs have already been merged. Could we considered this issue complete? 🤩

**Comment by verbman** [comment]
Yes!
